from independentCascade import IndependentCascadesModel
from weightedCascade import WeightedCascadeModel
from heuristics import degreeDiscount, singleDegreeDiscount, degreeSeedset, randomSeedset
from DiffusionModels import loadAmazon, loadGithub, loadArxiv, linearThreshold, weightedCascade, independentCascade
from newWeightedCascade import NewWeightedCascadeModel