from .randomheuristic import randomSeedsetUniform, randomSeedsetNonUniform
from .degree import degreeSeedsetUniform, degreeSeedsetNonUniform
from .singlediscount import singleDegreeDiscountUniform, singleDegreeDiscountNonUniform
from .degreediscount import degreeDiscountUniform, degreeDiscountNonUniform
